image:
  name: node:20

pipelines:
  default:
    - step:
        name: Build & deploy static web
        runs-on:
          - self.hosted
          - linux
        script:
          - apt-get update && apt-get install -y unzip curl
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip awscliv2.zip
          - ./aws/install
          - npm install -g pnpm@10.5.2
          - pnpm install --frozen-lockfile
          - pnpm run build:versioned
          # - DEPLOY_DATE=$(TZ='Asia/Bangkok' date +'%d-%m-%Y')
          - aws s3 sync dist/ s3://$S3_BUCKET_NAME/
          - echo "Clear cache on CloudFront"
          - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths /index.html
          - echo "Clean up"
          - rm -rf node_modules dist .pnpm-store || true
