image:
  name: node:20

pipelines:
  default:
    - step:
        name: Build & deploy static web
        runs-on:
          - self.hosted
          - linux
        script:
          - npm install -g pnpm@10.5.2
          - pnpm install --frozen-lockfile
          - pnpm run build:versioned
          - DEPLOY_DATE=$(TZ='Asia/Bangkok' date +'%d-%m-%Y')
          - aws s3 sync dist/ s3://$S3_BUCKET_NAME/$DEPLOY_DATE/
          - aws s3 cp dist/index.html s3://$S3_BUCKET_NAME/index.html
          - echo "Clear cache on CloudFront"
          - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths /index.html
          - echo "Clean up"
          - rm -rf node_modules dist .pnpm-store || true
